### ISSUE TITLE
InnerEye-CreateDataSet for Linux + other suggestions

### ISSUE THREAD

**Issue by athanell** [microsoft/InnerEye-CreateDataset#24]
Hello, 
Is there an option to call the create-dataset-utility on a linux environment (through the bash)? If yes can I find somewhere documentation (i.e. how to build the binary from source c code)?

**_Suggestion1:_** The utility gives the user the option to "restructure" ones nifti images+segmentations.  The result will be a proper folder structure, nomenclature and  modifications (normalization etc) of the nifti images+segmentations to adhere to the constraints of the innereye-deeplearning.
Example: 
``` bash
init_images/
├── HUSAH150_ANON0005_ax0.nii.gz (this is a head ct volume)
├── HUSAH150_ANON0005_ax0_seg.nii.gz (this is its corresponding lesion segmentation)
├── HUSAH150_ANON0008_ax0.nii.gz
├── HUSAH150_ANON0008_ax0_seg.nii.gz
├── HUSAH150_ANON0023_ax0.nii.gz
└── HUSAH150_ANON0023_ax0_seg.nii.gz

restruct_images/
├── subjectID1
│   ├── blood.nii.gz
│   └── head.nii.gz
├── subjectID2
│   ├── blood.nii.gz
│   └── head.nii.gz
└── subjectID3
    ├── blood.nii.gz
    └── head.nii.gz
```
_Why:_ It is not necessary that the users initial image+segmentation sets will be in a DICOM format. 

**_Suggestion2:_** For the case where the image+segmentation sets are in DICOM please consider the option of adding a proper DICOM IOD for the **segmentations** in your options (more details in  [http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_A.51.html](url)  )
_Why:_ The RTStruct is an old format that has been created for radiation therapy. It creates planar contours (surfaces) instead of volumes. When the geometry of the  segmented structure is complex, converting the RTSTRUCT IOD to a binary labelmap (like in a typical nifti format segmentation with 0 values on all voxels that are of no interest and 1 for all the voxels of interest) will lead to mistakes and segmentation quality degradation. That's the reason modern segmentation software that can segment DICOM images will save the segmentations as SEG objects and not RTSTRUCT. 
Since though a lot of segmentation material exist in the form of RTSTRUCT IODs, the converter of RTSTRUCT to NIFTI of this utility will certainly be beneficial.

**Comment by Shruthi42** [comment]
Hi @athanell, thank you for the suggestions. At present, we are working on a python package which will perform conversion between DICOM-RT and NIFTI and the other way around. This should provide better support for Linux and it will also be easier to implement your first suggestion as a python script. Would this help you?

Regarding your suggestion of adding support for the DICOM IOD for segmentation, one possible option is to add direct support in the [InnerEye-DeepLearning](https://github.com/microsoft/InnerEye-DeepLearning) repository. Could you create an issue there?

**Comment by athanell** [comment]
Sure @Shruthi42

**Comment by athanell** [comment]
> Hi @athanell, thank you for the suggestions. At present, we are working on a python package which will perform conversion between DICOM-RT and NIFTI and the other way around. This should provide better support for Linux and it will also be easier to implement your first suggestion as a python script. Would this help you?

If I got it correctly, currently what the Windows CreateDataSet utility does is: DICOM-RT(segmentation)/DICOM(image) -> convert2nifti + normalizing + Folder&FileRenaming -> NIFTI (ready to be ingested by InnerEye)

I was thinking that if the user works with NIFTI instead of DICOM then the utility could do something 

NIFTI -> normalizing + Folder&FileRenaming -> NIFTI (ready to be ingested by InnerEye)


> Regarding your suggestion of adding support for the DICOM IOD for segmentation, one possible option is to add direct support in the [InnerEye-DeepLearning](https://github.com/microsoft/InnerEye-DeepLearning) repository. Could you create an issue there?

Sure @Shruthi42

**Comment by ant0nsc** [comment]
Hi @athanell, If I get your use case correctly, it means that you have a CT in Nifti format, and a multi-label segmentation map per scan (that contains all the target structures). You'd like that multi-label segmentation to be converted to binary masks, right?
There are loads of different ways how segmentations can exist. It will be difficult for us to support all those. This specific conversion should be easily achievable with a small python script.

**Comment by athanell** [comment]
> Hi @athanell, If I get your use case correctly, it means that you have a CT in Nifti format, and a multi-label segmentation map per scan (that contains all the target structures). You'd like that multi-label segmentation to be converted to binary masks, right?

Hi @ant0nsc , I was not referring to multi-label segmentations. I hope I can make it a bit more clear with an example: 

**Assumption:** 2 subjects with a CT volume in a nifti format. For each of these 2 subjects a binary (one-label) segmentation mask exists:
**Data:** subject1_ct.nii.gz , subjec1_ct_seg.nii.gz, subject2_ct.nii.gz, subject2_ct_seg.nii.gz
**DataInfo:**  These 2 subjects  **_DO NOT_**   adhere to the following constraints:

- All images (across all subjects) must have already undergone geometric normalization, i.e., all images must have approximately the same voxel size. ( this is necessary according to https://github.com/microsoft/InnerEye-DeepLearning/blob/master/docs/creating_dataset.md)

So if the user wants to make sure that these 2 subjects along with their segmentations adhere to the inner eyes restrains , he could run a script, be it bash (useful if available) or windows that will do all the necessary geometric normalizations and file renaming.  

It could be called like: 

``` bash
#Windows Call
InnerEye.CreateDataset.Runner.exe dataset --datasetRootDirectory=<path to directory holding all datasets> --niftiDatasetDirectoryPrepped4InnerEye=<name of the folder to write to> --niftiDatasetDirectory=<name of nifti dataset to be normalized and renamed appropriately>
``` 

``` bash
#Linux Call
InnerEye_CreateDataset_Runner_Dataset.sh  --datasetRootDirectory=<path to directory holding all datasets> --niftiDatasetDirectoryPrepped4InnerEye=<name of the folder to write to> --niftiDatasetDirectory=<name of nifti dataset to be normalized and renamed appropriately>
``` 
 After the completion of the script(s) above, the two subjects (and their segmentations) are normalized and renamed as InnerEye expects them to be before ingesting them for training.

```bash
ImagesPrepped4InnerEye/
├── 0
│   ├── ct.nii.gz # normalized with the same vox size
│   └── seg.nii.gz #normalized with the same vox size
├── 1
│   ├── ct.nii.gz #normalized with the same vox size
│   └── seg.nii.gz #normalized with the same vox size

``` 

> There are loads of different ways how segmentations can exist. It will be difficult for us to support all those. This specific conversion should be easily achievable with a small python script.

I totally agree. If the user knows the exact details of the normalization process, one can do this data preparation. Some extra information that I thought it would be helpful to know for that is: 

- _"All images must have approximately the same voxel size_ " Does this mean the same isotropic voxels for every subject? What happens if the bounding box is not preserved after the resampling?  What kind of interpolation to use for resampling? Any limitations with the inplane resolution? Should it follow the average resolution of all the available subjects? the min? the max?

**Comment by ant0nsc** [comment]
@athanell , thanks for clarifying. As you are rightly saying at the end, there are loads of open questions around geometric normalization (i.e., getting everything to be the same voxel size). We have ourselves seen rather weird artefacts if that is not conducted very carefully. It's a can of worms, essentially. If you think you have a reliable solution available, we'd be more than happy to add that to this repository.
All images having the same voxel size does _not_ mean they should be isotropic. There are no limitations to the in-plane resolution - just that it should be roughly the same across all subjects.

**Comment by athanell** [comment]
> @athanell , thanks for clarifying. As you are rightly saying at the end, there are loads of open questions around geometric normalization (i.e., getting everything to be the same voxel size). We have ourselves seen rather weird artefacts if that is not conducted very carefully. It's a can of worms, essentially. If you think you have a reliable solution available, we'd be more than happy to add that to this repository.

@ant0nsc unfortunately I don't have any reliable solution. I was trying to replicate in linux with a python script what the InnerEye-CreateDataset does so that I won't have to use a windows VM just for the dataprep. Such questions came along, as I begun implementing it, which I couldn't answer since I didn't have enough information on how each step is made precisely.
  
> All images having the same voxel size does _not_ mean they should be isotropic. There are no limitations to the in-plane resolution - just that it should be roughly the same across all subjects.

Ok Thanks @ant0nsc
